# ref: https://github.com/vercel/next.js/blob/canary/examples/with-docker-compose/docker-compose.dev.yml

name: ai-learn-landing-page-dev
services:
  landing-page-app:
    container_name: landing-page
    image: ai-learn-landing-page-dev
    build:
      context: .
      dockerfile: "docker/multi-stage/Dockerfile"
      target: development

    # TODO: Set the environment variables in the .env file
    # Set environment variables directly in the docker-compose file
    # environment:
    # ENV_VARIABLE: ${ENV_VARIABLE}
    # NEXT_PUBLIC_ENV_VARIABLE: ${NEXT_PUBLIC_ENV_VARIABLE}

    # Set environment variables based on the .env file
    # env_file:
    # - .env

    restart: unless-stopped
    environment:
      - NODE_ENV=development

    volumes:
      - ./app:/usr/src/app/src
      - ./public:/usr/src/app/public

    ports:
      - ${PORT}:${PORT}

    command:
      - /bin/sh
      - -c
      - |
        pnpm dev

    networks:
      - learn_cloud_network

networks:
  learn_cloud_network:
    driver: bridge
