# ref: https://github.com/vercel/next.js/blob/canary/examples/with-docker-compose/docker-compose.prod.yml

version: "3.8"

name: ai-learn-landing-page-prod
services:
    next-app:
        container_name: landing-page
        image: ai-learn-landing-page-prod
        build:
            context: .
            dockerfile: "docker/production/Dockerfile"
        environment:
            NODE_ENV: production
        restart: always
        ports:
            - 3000:3000
