version: "3.8"

services:
    landing-page:
        container_name: landing-page-prod
        build:
            context: .
            dockerfile: "docker/production/Dockerfile"
        environment:
            NODE_ENV: production
        restart: unless-stopped
        ports:
            - 3000:3000
