# ref: https://github.com/vercel/next.js/blob/canary/examples/with-docker-compose/docker-compose.dev.yml

name: ai-learn-landing-page-staging
services:
  landing-page-app:
    container_name: landing-page
    image: ${DOCKER_REGISTRY}/${PROJET_NAME}:latest
    build:
      context: .
      dockerfile: "docker/multi-stage/Dockerfile"
      target: production
    restart: always
    volumes:
      - ./app:/usr/src/app/src
      - ./public:/usr/src/app/public
    ports:
      - ${PORT}:${PORT}
