# ref: https://github.com/vercel/next.js/blob/canary/examples/with-docker-compose/docker-compose.prod.yml

name: ai-learn-landing-page-prod
services:
  landing-page-app:
    container_name: landing-page
    image: ${DOCKER_REGISTRY}/${PROJET_NAME}:latest
    build:
      context: .
      dockerfile: "docker/multi-stage/Dockerfile"
      target: production
    restart: always
    ports:
      - ${PORT}:${PORT}

    networks:
      - learn_cloud_network

networks:
  learn_cloud_network:
    driver: bridge
